builds:
  - skip: true

release:
  extra_files:
    - gojs-cvss.js
    - gojs-cvss.js.map

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

source:
  enabled: true
  files:
    - gojs-cvss.js
    - gojs-cvss.js.map

checksum: {}

sboms:
  - artifacts: source
