name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  unit-tests:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
        include:
          - update-coverage: true
    runs-on: ${{ matrix.platform }}
    needs: [setup]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install gopherjs
        run: go install github.com/gopherjs/gopherjs@v1.18.0-beta3
      - name: Transpile gojs-cvss
        run: gopherjs build .

      - name: Run go test
        run: go test -v -race -coverprofile coverage.txt ./...
      
      - name: Upload coverage to Coveralls
        if: ${{ matrix.update-coverage }}
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

  go-lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.x
      
      - name: go-lint
        uses: golangci/golangci-lint-action@v5
